### 获取所有服务实例
GET http://localhost:8445/getInstances?serviceId=abc

### 注册服务实例
PUT http://localhost:8445/register?serviceId=abc
Content-Type: application/json

{
  "host": "127.0.0.1",
  "port": 8082,
  "attributes": {
    "a": "B"
  }
}

### 注销服务实例
DELETE http://localhost:8444/unregister?serviceId=abc
Content-Type: application/json

{
  "host": "127.0.0.1",
  "port": 8081,
  "attributes": {
    "a": "B"
  }
}

### 获取服务版本
GET http://localhost:8445/version?serviceId=abc

### 获取服务实例的数据快照
GET http://localhost:8444/snapshot

### 获取所有集群节点实例
GET http://localhost:8444/clusterServerList